name: SunDownShowdown
main: com.kgeezy.sundownshowdown.SunDownShowdown
version: 1.0.0
api-version: 1.13
commands:
  chest:
    description: places a chest filled with loot
    usage: /<command>
  restock:
    description: restocks chests for the showdown
    usage: /<command>
  forcestart:
    description: force starts the Showdown
    usage: /<command>