name: SunDownShowdown
main: com.kgeezy.sundownshowdown.SundownShowdown
version: 1.0.0
api-version: 1.13
commands:
  showdown:
    usage: /<command> [chest | start | enable | disable] [add | remove | restock] [all]
    description: Main showdown command.